# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edf.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(699, 747)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.pushButtonFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFile.setObjectName("pushButtonFile")
        self.verticalLayout_2.addWidget(self.pushButtonFile)
        self.pushButtonOpenCsv = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOpenCsv.setObjectName("pushButtonOpenCsv")
        self.verticalLayout_2.addWidget(self.pushButtonOpenCsv)
        self.pushButtonLoadRTcsv = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonLoadRTcsv.setObjectName("pushButtonLoadRTcsv")
        self.verticalLayout_2.addWidget(self.pushButtonLoadRTcsv)
        self.labelEDFFile = QtWidgets.QLabel(self.centralwidget)
        self.labelEDFFile.setMaximumSize(QtCore.QSize(400, 16777215))
        self.labelEDFFile.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.labelEDFFile.setText("")
        self.labelEDFFile.setWordWrap(True)
        self.labelEDFFile.setObjectName("labelEDFFile")
        self.verticalLayout_2.addWidget(self.labelEDFFile)
        self.pushButtonPlot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPlot.setObjectName("pushButtonPlot")
        self.verticalLayout_2.addWidget(self.pushButtonPlot)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableViewEdf_UI = QtWidgets.QTableView(self.centralwidget)
        self.tableViewEdf_UI.setObjectName("tableViewEdf_UI")
        self.verticalLayout.addWidget(self.tableViewEdf_UI)
        self.pushButtonSaveRtToFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSaveRtToFile.setObjectName("pushButtonSaveRtToFile")
        self.verticalLayout.addWidget(self.pushButtonSaveRtToFile)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 699, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "EDF"))
        self.pushButtonFile.setText(_translate("MainWindow", "Open EDF"))
        self.pushButtonOpenCsv.setText(_translate("MainWindow", "Open FSR, BUTTON csv"))
        self.pushButtonLoadRTcsv.setText(_translate("MainWindow", "Load RTS csv"))
        self.pushButtonPlot.setText(_translate("MainWindow", "PLOT"))
        self.pushButtonSaveRtToFile.setText(_translate("MainWindow", "SAVE RT"))
